# Generated by Django 5.2.6 on 2025-09-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('severity', models.CharField(max_length=50)),
                ('likelihood', models.CharField(max_length=50)),
                ('mitigation_plan', models.TextField(blank=True)),
            ],
        ),
    ]
